---
Resources:
  techno-lambda-order-management:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 512
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 30
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-order-management"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-order-management"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-process-payment:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 512
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: "LambdaFunctionTechnolambdaprocesspaymentCodeS3BucketmXUa0"
        ZipFile:
          Ref: "LambdaFunctionTechnolambdaprocesspaymentCodeZipFile3FgaD"
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-process-payment"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-process-payment"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-update-inventory:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 256
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-update-inventory"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-update-inventory"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-send-notification:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Timeout: 60
    Properties:
      MemorySize: 256
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-send-notification"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-send-notification"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-generate-report:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 1024
      Timeout: 120
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-generate-report"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-generate-report"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-init-db:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 512
      Description: ""
      Timeout: 300
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-init-db"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-init-db"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  techno-lambda-health-check:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    Properties:
      MemorySize: 128
      Description: ""
      Timeout: 10
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        S3Bucket:
          Ref: ""
        ZipFile:
          Ref: ""
      Role: "arn:aws:iam::129200883043:role/LabRole"
      FileSystemConfigs: []
      FunctionName: "techno-lambda-health-check"
      Runtime: "python3.11"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/techno-lambda-health-check"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
      Layers:
      - "arn:aws:lambda:us-east-1:129200883043:layer:techno-layer-dependencies:1"
  SNSTopicTechnosnsordernotifications:
    Type: "AWS::SNS::Topic"
    DeletionPolicy: "Delete"
    Properties:
      TracingConfig: "PassThrough"
      DisplayName: "techno-sns-order-notifications"
      FifoTopic: false
      Subscription:
      - Endpoint: "handi@seamolec.org"
        Protocol: "email"
      Tags:
      - Value: "techno-sns-order-notifications"
        Key: "Name"
      ArchivePolicy: {}
      TopicName: "techno-sns-order-notifications"